// Figures calculated from the uploaded UCI dataset.
// "real" means the held-out original sessions.
// "synthetic" means sessions generated by the Bayesian model.

const study = {
    training: 9864,
    holdout: 2466,
    syntheticCount: 2466,
    realPurchaseRate: 0.154095701540957,
    syntheticPurchaseRate: 0.15450121654501217,
    largestSegmentGap: 0.05183363148479428,

    sections: [
        {
            title: "Visitor type",
            rows: [
                ["Returning", 0.14028436018957346, 0.15004748338081672, 2110, 0.8556366585563666, 0.8540145985401459],
                ["New", 0.23952095808383234, 0.19090909090909092, 334, 0.1354420113544201, 0.13381995133819952],
                ["Other", 0.18181818181818182, 0.06666666666666667, 22, 0.008921330089213302, 0.012165450121654502]
            ]
        },
        {
            title: "Product pages viewed",
            rows: [
                ["0–5", 0.03773584905660377, 0.04821802935010482, 477, 0.19343065693430658, 0.19343065693430658],
                ["6–15", 0.11764705882352941, 0.11707317073170732, 629, 0.2550689375506894, 0.24939172749391728],
                ["16–40", 0.1925064599483204, 0.1881918819188192, 774, 0.31386861313868614, 0.32968369829683697],
                ["41+", 0.23720136518771331, 0.23707664884135474, 586, 0.23763179237631793, 0.22749391727493917]
            ]
        },
        {
            title: "Exit rate band",
            rows: [
                ["Low", 0.22662889518413598, 0.22149122807017543, 1412, 0.5725871857258719, 0.5547445255474452],
                ["Medium", 0.07603092783505154, 0.08508014796547472, 776, 0.3146796431467964, 0.3288726682887267],
                ["High", 0.0035971223021582736, 0.0313588850174216, 278, 0.11273317112733171, 0.11638280616382807]
            ]
        },
        {
            title: "Traffic type",
            rows: [
                ["1", 0.12401574803149606, 0.11496746203904555, 508, 0.2060016220600162, 0.18694241686942417],
                ["2", 0.20282413350449294, 0.20525657071339173, 779, 0.31589618815896187, 0.3240064882400649],
                ["3", 0.08333333333333333, 0.09307875894988067, 396, 0.16058394160583941, 0.16991078669910786],
                ["4", 0.16346153846153846, 0.11162790697674418, 208, 0.08434712084347121, 0.08718572587185726],
                ["Other", 0.16, 0.17657342657342656, 575, 0.23317112733171128, 0.23195458231954583]
            ]
        }
    ]
};

function percent(value) {
    return (value * 100).toFixed(1) + "%";
}

document.querySelector("#cards").innerHTML = [
    ["Training sessions", study.training.toLocaleString(), "Original data"],
    ["Held-out sessions", study.holdout.toLocaleString(), "Original data"],
    ["Synthetic sessions", study.syntheticCount.toLocaleString(), "Generated"],
    [
        "Purchase rate gap",
        ((study.syntheticPurchaseRate - study.realPurchaseRate) * 100).toFixed(1) + " pp",
        "Synthetic minus holdout"
    ]
].map(([label, value, detail]) => `
  <div class="card">
    <small>${label}</small>
    <strong>${value}</strong>
    <span>${detail}</span>
  </div>
`).join("");

function drawRows(rows, showProportions) {
    return rows.map(row => {
        const [label, realRate, syntheticRate, count, realShare, syntheticShare] = row;
        const real = showProportions ? realShare : realRate;
        const synthetic = showProportions ? syntheticShare : syntheticRate;
        const scale = showProportions ? 1 : 0.5;
        const countText = showProportions ? "" : ` · n=${count}`;

        return `
      <div class="row">
        <div class="line">
          <b>${label}</b>
          <em>${percent(real)} · ${percent(synthetic)}${countText}</em>
        </div>
        <div class="track">
          <div class="bar real" style="width:${Math.min(100, real / scale * 100)}%"></div>
        </div>
        <div class="track">
          <div class="bar syn" style="width:${Math.min(100, synthetic / scale * 100)}%"></div>
        </div>
      </div>
    `;
    }).join("");
}

function selectSection(index) {
    document.querySelectorAll("#tabs button").forEach((button, buttonIndex) => {
        button.classList.toggle("active", buttonIndex === index);
    });

    const rows = study.sections[index].rows;
    document.querySelector("#segment").innerHTML = drawRows(rows, false);
    document.querySelector("#marginal").innerHTML = drawRows(rows, true);
}

document.querySelector("#tabs").innerHTML = study.sections
    .map((section, index) => `
    <button type="button" data-index="${index}">${section.title}</button>
  `)
    .join("");

document.querySelectorAll("#tabs button").forEach(button => {
    button.addEventListener("click", () => {
        selectSection(Number(button.dataset.index));
    });
});

selectSection(1);

document.querySelector("#finding").textContent =
    `The held-out purchase rate is ${percent(study.realPurchaseRate)}; ` +
    `the synthetic rate is ${percent(study.syntheticPurchaseRate)}. ` +
    `Among displayed segments with at least 30 held-out sessions, ` +
    `the largest absolute purchase-rate gap is ` +
    `${(study.largestSegmentGap * 100).toFixed(1)} percentage points. ` +
    `Matching the overall total alone is insufficient evidence that ` +
    `synthetic data retains useful relationships.`;